version: 0.0
os: linux
files:
  - source: helloworld.js
    destination: /usr/local/helloworld/helloworld.js
  - source: scripts/helloworld.conf
    destination: /etc/init/helloworld.conf
hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 3600
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3600
