version: 0.1
phases:
  pre_build:
    commands:
      - find .
      - printf "%s:%s" "$REPOSITORY_URI" "$(cat .git/refs/heads/master)" > /tmp/build_tag.out
      - printf '{"tag":"%s"}' "$(cat .git/refs/heads/master)" > /tmp/build.json
      - $(aws ecr get-login)
  build:
    commands:
      - docker build -t "$(cat /tmp/build_tag.out)" .
  post_build:
    commands:
      - docker push "$(cat /tmp/build_tag.out)"
      - aws ecr batch-get-image --repository-name $REPOSITORY_NAME --image-ids imageTag=foobar --query 'images[].imageManifest' --output text > /tmp/latest_manifest.json
      - aws ecr put-image --repository-name $REPOSITORY_NAME --image-tag latest --image-manifest (cat /tmp/latest_manifest.json)
artifacts:
  files: /tmp/build.json
  discard-paths: yes
